name: VideoInvoice
version: "3.8"

services:
  node_server:
    build:
      context: ./node_server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./node_server/.env
    environment:
      - RUST_AI_URL=http://rust_engine:3000/api/ai
      - PDF_ENGINE_URL=http://pdf_engine:5000
    depends_on:
      - rust_engine
      - pdf_engine
    networks:
      - videoinvoice_network

  pdf_engine:
    build:
      context: ./pdf_engine
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    networks:
      - videoinvoice_network
    restart: unless-stopped

  rust_engine:
    build:
      context: ./rust_engine
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./rust_engine/.env
    networks:
      - videoinvoice_network

networks:
  videoinvoice_network:
    driver: bridge
